development:
  dialect: mysql # 使用するRDBMS
  datasource: user:password@tcp(db:3306)/todo_db?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=true
  dir: Backend/db/migrations # マイグレーションファイルのあるディレクトリ
  table: migrations # マイグレーション履歴を保存するテーブル
