version: "3.7"
services:
  db:
    image: mysql:8.0
    tty: true
    platform: linux/x86_64
    container_name: todo_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - todo-db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=todo_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

volumes:
  todo-db-volume:
