version: '3' # composeファイルのバージョン
services:
  go: # サービス名
    build: # ビルドに使うDockerfileの場所
      context: .             # コンテキストをルートディレクトリに指定
      dockerfile: Dockerfile  # dockerfileの場所を直接指定
    stdin_open: true
    tty: true # コンテナの永続化
    volumes:
      - .:/go/src/app # ホストからコンテナにマウント
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_HOST: todo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  db:
    image: mysql:8.0
    tty: true
    platform: linux/x86_64
    container_name: todo_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - todo-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  todo-db-volume:

